<?php

use Illuminate\Database\Seeder;

/**
 * Class LanguagesTableSeeder
 */
class LanguagesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('languages')->insert([ 'code' => 'aa', 'name' => 'Afar' ]);
        DB::table('languages')->insert([ 'code' => 'ab', 'name' => 'Abjasio ' ]);
        DB::table('languages')->insert([ 'code' => 'ae', 'name' => 'Avéstico' ]);
        DB::table('languages')->insert([ 'code' => 'af', 'name' => 'Afrikáans' ]);
        DB::table('languages')->insert([ 'code' => 'ak', 'name' => 'Akano' ]);
        DB::table('languages')->insert([ 'code' => 'am', 'name' => 'Amhárico' ]);
        DB::table('languages')->insert([ 'code' => 'an', 'name' => 'Aragonés' ]);
        DB::table('languages')->insert([ 'code' => 'ar', 'name' => 'Árabe' ]);
        DB::table('languages')->insert([ 'code' => 'as', 'name' => 'Asamés' ]);
        DB::table('languages')->insert([ 'code' => 'av', 'name' => 'Avar' ]);
        DB::table('languages')->insert([ 'code' => 'ay', 'name' => 'Aimara' ]);
        DB::table('languages')->insert([ 'code' => 'az', 'name' => 'Azerí' ]);
        DB::table('languages')->insert([ 'code' => 'ba', 'name' => 'Baskir' ]);
        DB::table('languages')->insert([ 'code' => 'be', 'name' => 'Bielorruso' ]);
        DB::table('languages')->insert([ 'code' => 'bg', 'name' => 'Búlgaro' ]);
        DB::table('languages')->insert([ 'code' => 'bh', 'name' => 'Bhoyapurí' ]);
        DB::table('languages')->insert([ 'code' => 'bi', 'name' => 'Bislama' ]);
        DB::table('languages')->insert([ 'code' => 'bm', 'name' => 'Bambara' ]);
        DB::table('languages')->insert([ 'code' => 'bn', 'name' => 'Bengalí' ]);
        DB::table('languages')->insert([ 'code' => 'bo', 'name' => 'Tibetano' ]);
        DB::table('languages')->insert([ 'code' => 'br', 'name' => 'Bretón' ]);
        DB::table('languages')->insert([ 'code' => 'bs', 'name' => 'Bosnio' ]);
        DB::table('languages')->insert([ 'code' => 'ca', 'name' => 'Catalán' ]);
        DB::table('languages')->insert([ 'code' => 'ce', 'name' => 'Checheno' ]);
        DB::table('languages')->insert([ 'code' => 'ch', 'name' => 'Chamorro' ]);
        DB::table('languages')->insert([ 'code' => 'co', 'name' => 'Corso' ]);
        DB::table('languages')->insert([ 'code' => 'cr', 'name' => 'Cree' ]);
        DB::table('languages')->insert([ 'code' => 'cs', 'name' => 'Checo' ]);
        DB::table('languages')->insert([ 'code' => 'cu', 'name' => 'Eslavo eclesiástico antiguo' ]);
        DB::table('languages')->insert([ 'code' => 'cv', 'name' => 'Chuvasio' ]);
        DB::table('languages')->insert([ 'code' => 'cy', 'name' => 'Galés' ]);
        DB::table('languages')->insert([ 'code' => 'da', 'name' => 'Danés' ]);
        DB::table('languages')->insert([ 'code' => 'de', 'name' => 'Alemán' ]);
        DB::table('languages')->insert([ 'code' => 'dv', 'name' => 'Maldivo' ]);
        DB::table('languages')->insert([ 'code' => 'dz', 'name' => 'Dzongkha' ]);
        DB::table('languages')->insert([ 'code' => 'ee', 'name' => 'Ewé' ]);
        DB::table('languages')->insert([ 'code' => 'el', 'name' => 'Griego' ]);
        DB::table('languages')->insert([ 'code' => 'en', 'name' => 'Inglés' ]);
        DB::table('languages')->insert([ 'code' => 'eo', 'name' => 'Esperanto' ]);
        DB::table('languages')->insert([ 'code' => 'es', 'name' => 'Español' ]);
        DB::table('languages')->insert([ 'code' => 'et', 'name' => 'Estonio' ]);
        DB::table('languages')->insert([ 'code' => 'eu', 'name' => 'Euskera' ]);
        DB::table('languages')->insert([ 'code' => 'fa', 'name' => 'Persa' ]);
        DB::table('languages')->insert([ 'code' => 'ff', 'name' => 'Fula' ]);
        DB::table('languages')->insert([ 'code' => 'fi', 'name' => 'Finés' ]);
        DB::table('languages')->insert([ 'code' => 'fj', 'name' => 'Fiyiano' ]);
        DB::table('languages')->insert([ 'code' => 'fo', 'name' => 'Feroés' ]);
        DB::table('languages')->insert([ 'code' => 'fr', 'name' => 'Francés' ]);
        DB::table('languages')->insert([ 'code' => 'fy', 'name' => 'Frisón' ]);
        DB::table('languages')->insert([ 'code' => 'ga', 'name' => 'Irlandés' ]);
        DB::table('languages')->insert([ 'code' => 'gd', 'name' => 'Gaélico escocés' ]);
        DB::table('languages')->insert([ 'code' => 'gl', 'name' => 'Gallego' ]);
        DB::table('languages')->insert([ 'code' => 'gn', 'name' => 'Guaraní' ]);
        DB::table('languages')->insert([ 'code' => 'gu', 'name' => 'Guyaratí' ]);
        DB::table('languages')->insert([ 'code' => 'gv', 'name' => 'Manés' ]);
        DB::table('languages')->insert([ 'code' => 'ha', 'name' => 'Hausa' ]);
        DB::table('languages')->insert([ 'code' => 'he', 'name' => 'Hebreo' ]);
        DB::table('languages')->insert([ 'code' => 'hi', 'name' => 'Hindi' ]);
        DB::table('languages')->insert([ 'code' => 'ho', 'name' => 'Hiri motu' ]);
        DB::table('languages')->insert([ 'code' => 'hr', 'name' => 'Croata' ]);
        DB::table('languages')->insert([ 'code' => 'ht', 'name' => 'Haitiano' ]);
        DB::table('languages')->insert([ 'code' => 'hu', 'name' => 'Húngaro' ]);
        DB::table('languages')->insert([ 'code' => 'hy', 'name' => 'Armenio' ]);
        DB::table('languages')->insert([ 'code' => 'hz', 'name' => 'Herero' ]);
        DB::table('languages')->insert([ 'code' => 'ia', 'name' => 'Interlingua' ]);
        DB::table('languages')->insert([ 'code' => 'id', 'name' => 'Indonesio' ]);
        DB::table('languages')->insert([ 'code' => 'ie', 'name' => 'Occidental' ]);
        DB::table('languages')->insert([ 'code' => 'ig', 'name' => 'Igbo' ]);
        DB::table('languages')->insert([ 'code' => 'ii', 'name' => 'Yi de Sichuán' ]);
        DB::table('languages')->insert([ 'code' => 'ik', 'name' => 'Iñupiaq' ]);
        DB::table('languages')->insert([ 'code' => 'io', 'name' => 'Ido' ]);
        DB::table('languages')->insert([ 'code' => 'is', 'name' => 'Islandés' ]);
        DB::table('languages')->insert([ 'code' => 'it', 'name' => 'Italiano' ]);
        DB::table('languages')->insert([ 'code' => 'iu', 'name' => 'Inuktitut' ]);
        DB::table('languages')->insert([ 'code' => 'ja', 'name' => 'Japonés' ]);
        DB::table('languages')->insert([ 'code' => 'jv', 'name' => 'Javanés' ]);
        DB::table('languages')->insert([ 'code' => 'ka', 'name' => 'Georgiano' ]);
        DB::table('languages')->insert([ 'code' => 'kg', 'name' => 'Kongo' ]);
        DB::table('languages')->insert([ 'code' => 'ki', 'name' => 'Kikuyu' ]);
        DB::table('languages')->insert([ 'code' => 'kj', 'name' => 'Kuanyama' ]);
        DB::table('languages')->insert([ 'code' => 'kk', 'name' => 'Kazajo' ]);
        DB::table('languages')->insert([ 'code' => 'kl', 'name' => 'Groenlandés' ]);
        DB::table('languages')->insert([ 'code' => 'km', 'name' => 'Camboyano' ]);
        DB::table('languages')->insert([ 'code' => 'kn', 'name' => 'Canarés' ]);
        DB::table('languages')->insert([ 'code' => 'ko', 'name' => 'Coreano' ]);
        DB::table('languages')->insert([ 'code' => 'kr', 'name' => 'Kanuri' ]);
        DB::table('languages')->insert([ 'code' => 'ks', 'name' => 'Cachemiro' ]);
        DB::table('languages')->insert([ 'code' => 'ku', 'name' => 'Kurdo' ]);
        DB::table('languages')->insert([ 'code' => 'kv', 'name' => 'Komi' ]);
        DB::table('languages')->insert([ 'code' => 'kw', 'name' => 'Córnico' ]);
        DB::table('languages')->insert([ 'code' => 'ky', 'name' => 'Kirguís' ]);
        DB::table('languages')->insert([ 'code' => 'la', 'name' => 'Latín' ]);
        DB::table('languages')->insert([ 'code' => 'lb', 'name' => 'Luxemburgués' ]);
        DB::table('languages')->insert([ 'code' => 'lg', 'name' => 'Luganda' ]);
        DB::table('languages')->insert([ 'code' => 'li', 'name' => 'Limburgués' ]);
        DB::table('languages')->insert([ 'code' => 'ln', 'name' => 'Lingala' ]);
        DB::table('languages')->insert([ 'code' => 'lo', 'name' => 'Lao' ]);
        DB::table('languages')->insert([ 'code' => 'lt', 'name' => 'Lituano' ]);
        DB::table('languages')->insert([ 'code' => 'lu', 'name' => 'Luba-katanga' ]);
        DB::table('languages')->insert([ 'code' => 'lv', 'name' => 'Letón' ]);
        DB::table('languages')->insert([ 'code' => 'mg', 'name' => 'Malgache' ]);
        DB::table('languages')->insert([ 'code' => 'mh', 'name' => 'Marshalés' ]);
        DB::table('languages')->insert([ 'code' => 'mi', 'name' => 'Maorí' ]);
        DB::table('languages')->insert([ 'code' => 'mk', 'name' => 'Macedonio' ]);
        DB::table('languages')->insert([ 'code' => 'ml', 'name' => 'Malayalam' ]);
        DB::table('languages')->insert([ 'code' => 'mn', 'name' => 'Mongol' ]);
        DB::table('languages')->insert([ 'code' => 'mr', 'name' => 'Maratí' ]);
        DB::table('languages')->insert([ 'code' => 'ms', 'name' => 'Malayo' ]);
        DB::table('languages')->insert([ 'code' => 'mt', 'name' => 'Maltés' ]);
        DB::table('languages')->insert([ 'code' => 'my', 'name' => 'Birmano' ]);
        DB::table('languages')->insert([ 'code' => 'na', 'name' => 'Nauruano' ]);
        DB::table('languages')->insert([ 'code' => 'nb', 'name' => 'Noruego bokmål' ]);
        DB::table('languages')->insert([ 'code' => 'nd', 'name' => 'Ndebele del norte' ]);
        DB::table('languages')->insert([ 'code' => 'ne', 'name' => 'Nepalí' ]);
        DB::table('languages')->insert([ 'code' => 'ng', 'name' => 'Ndonga' ]);
        DB::table('languages')->insert([ 'code' => 'nl', 'name' => 'Neerlandés' ]);
        DB::table('languages')->insert([ 'code' => 'nn', 'name' => 'Nynorsk' ]);
        DB::table('languages')->insert([ 'code' => 'no', 'name' => 'Noruego' ]);
        DB::table('languages')->insert([ 'code' => 'nr', 'name' => 'Ndebele del sur' ]);
        DB::table('languages')->insert([ 'code' => 'nv', 'name' => 'Navajo' ]);
        DB::table('languages')->insert([ 'code' => 'ny', 'name' => 'Chichewa' ]);
        DB::table('languages')->insert([ 'code' => 'oc', 'name' => 'Occitano' ]);
        DB::table('languages')->insert([ 'code' => 'oj', 'name' => 'Ojibwa' ]);
        DB::table('languages')->insert([ 'code' => 'om', 'name' => 'Oromo' ]);
        DB::table('languages')->insert([ 'code' => 'or', 'name' => 'Oriya' ]);
        DB::table('languages')->insert([ 'code' => 'os', 'name' => 'Osético' ]);
        DB::table('languages')->insert([ 'code' => 'pa', 'name' => 'Panyabí' ]);
        DB::table('languages')->insert([ 'code' => 'pi', 'name' => 'Pali' ]);
        DB::table('languages')->insert([ 'code' => 'pl', 'name' => 'Polaco' ]);
        DB::table('languages')->insert([ 'code' => 'ps', 'name' => 'Pastú' ]);
        DB::table('languages')->insert([ 'code' => 'pt', 'name' => 'Portugués' ]);
        DB::table('languages')->insert([ 'code' => 'qu', 'name' => 'Quechua' ]);
        DB::table('languages')->insert([ 'code' => 'rm', 'name' => 'Romanche' ]);
        DB::table('languages')->insert([ 'code' => 'rn', 'name' => 'Kirundi' ]);
        DB::table('languages')->insert([ 'code' => 'ro', 'name' => 'Rumano' ]);
        DB::table('languages')->insert([ 'code' => 'ru', 'name' => 'Ruso' ]);
        DB::table('languages')->insert([ 'code' => 'rw', 'name' => 'Ruandés' ]);
        DB::table('languages')->insert([ 'code' => 'sa', 'name' => 'Sánscrito' ]);
        DB::table('languages')->insert([ 'code' => 'sc', 'name' => 'Sardo' ]);
        DB::table('languages')->insert([ 'code' => 'sd', 'name' => 'Sindhi' ]);
        DB::table('languages')->insert([ 'code' => 'se', 'name' => 'Sami' ]);
        DB::table('languages')->insert([ 'code' => 'sg', 'name' => 'Sango' ]);
        DB::table('languages')->insert([ 'code' => 'si', 'name' => 'Cingalés' ]);
        DB::table('languages')->insert([ 'code' => 'sk', 'name' => 'Eslovaco' ]);
        DB::table('languages')->insert([ 'code' => 'sl', 'name' => 'Esloveno' ]);
        DB::table('languages')->insert([ 'code' => 'sm', 'name' => 'Samoano' ]);
        DB::table('languages')->insert([ 'code' => 'sn', 'name' => 'Shona' ]);
        DB::table('languages')->insert([ 'code' => 'so', 'name' => 'Somalí' ]);
        DB::table('languages')->insert([ 'code' => 'sq', 'name' => 'Albanés' ]);
        DB::table('languages')->insert([ 'code' => 'sr', 'name' => 'Serbio' ]);
        DB::table('languages')->insert([ 'code' => 'ss', 'name' => 'Suazi' ]);
        DB::table('languages')->insert([ 'code' => 'st', 'name' => 'Sesotho' ]);
        DB::table('languages')->insert([ 'code' => 'su', 'name' => 'Sundanés' ]);
        DB::table('languages')->insert([ 'code' => 'sv', 'name' => 'Sueco' ]);
        DB::table('languages')->insert([ 'code' => 'sw', 'name' => 'Suajili' ]);
        DB::table('languages')->insert([ 'code' => 'ta', 'name' => 'Tamil' ]);
        DB::table('languages')->insert([ 'code' => 'te', 'name' => 'Télugu' ]);
        DB::table('languages')->insert([ 'code' => 'tg', 'name' => 'Tayiko' ]);
        DB::table('languages')->insert([ 'code' => 'th', 'name' => 'Tailandés' ]);
        DB::table('languages')->insert([ 'code' => 'ti', 'name' => 'Tigriña' ]);
        DB::table('languages')->insert([ 'code' => 'tk', 'name' => 'Turcomano' ]);
        DB::table('languages')->insert([ 'code' => 'tl', 'name' => 'Tagalo' ]);
        DB::table('languages')->insert([ 'code' => 'tn', 'name' => 'Setsuana' ]);
        DB::table('languages')->insert([ 'code' => 'to', 'name' => 'Tongano' ]);
        DB::table('languages')->insert([ 'code' => 'tr', 'name' => 'Turco' ]);
        DB::table('languages')->insert([ 'code' => 'ts', 'name' => 'Tsonga' ]);
        DB::table('languages')->insert([ 'code' => 'tt', 'name' => 'Tártaro' ]);
        DB::table('languages')->insert([ 'code' => 'tw', 'name' => 'Twi' ]);
        DB::table('languages')->insert([ 'code' => 'ty', 'name' => 'Tahitiano' ]);
        DB::table('languages')->insert([ 'code' => 'ug', 'name' => 'Uigur' ]);
        DB::table('languages')->insert([ 'code' => 'uk', 'name' => 'Ucraniano' ]);
        DB::table('languages')->insert([ 'code' => 'ur', 'name' => 'Urdu' ]);
        DB::table('languages')->insert([ 'code' => 'uz', 'name' => 'Uzbeko' ]);
        DB::table('languages')->insert([ 'code' => 've', 'name' => 'Venda' ]);
        DB::table('languages')->insert([ 'code' => 'vi', 'name' => 'Vietnamita' ]);
        DB::table('languages')->insert([ 'code' => 'vo', 'name' => 'Volapük' ]);
        DB::table('languages')->insert([ 'code' => 'wa', 'name' => 'Valón' ]);
        DB::table('languages')->insert([ 'code' => 'wo', 'name' => 'Wolof' ]);
        DB::table('languages')->insert([ 'code' => 'xh', 'name' => 'Xhosa' ]);
        DB::table('languages')->insert([ 'code' => 'yi', 'name' => 'Yídish' ]);
        DB::table('languages')->insert([ 'code' => 'yo', 'name' => 'Yoruba' ]);
        DB::table('languages')->insert([ 'code' => 'za', 'name' => 'Chuan' ]);
        DB::table('languages')->insert([ 'code' => 'zh', 'name' => 'Chino' ]);
        DB::table('languages')->insert([ 'code' => 'zu', 'name' => 'Zulú' ]);
    }

}
